//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBookMan.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EBookMan.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap computer {
            get {
                object obj = ResourceManager.GetObject("computer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add binary {0}..
        /// </summary>
        internal static string ErrorAddFileFailed {
            get {
                return ResourceManager.GetString("ErrorAddFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding &apos;{0}&apos; to the database failed due to the database failure. Book is skipped..
        /// </summary>
        internal static string ErrorAddingBookFailed {
            get {
                return ResourceManager.GetString("ErrorAddingBookFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding new tags to the database failed. The tag is skipped..
        /// </summary>
        internal static string ErrorAddTagFailed {
            get {
                return ResourceManager.GetString("ErrorAddTagFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not move file {0} to the library folder. The file is left at its original location and the link to it is stored..
        /// </summary>
        internal static string ErrorMoveFileFailed {
            get {
                return ResourceManager.GetString("ErrorMoveFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not compress file {0}. Original version is used instead..
        /// </summary>
        internal static string ErrorZipFileFailed {
            get {
                return ResourceManager.GetString("ErrorZipFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Computer.
        /// </summary>
        internal static string MdbName {
            get {
                return ResourceManager.GetString("MdbName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library located on the local computer.
        /// </summary>
        internal static string MdbTooltip {
            get {
                return ResourceManager.GetString("MdbTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding book to the library....
        /// </summary>
        internal static string PromptAddingBook {
            get {
                return ResourceManager.GetString("PromptAddingBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding {0} to the library....
        /// </summary>
        internal static string PromptAddingFiles {
            get {
                return ResourceManager.GetString("PromptAddingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for duplicates....
        /// </summary>
        internal static string PromptCheckingDuplicates {
            get {
                return ResourceManager.GetString("PromptCheckingDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating book tags....
        /// </summary>
        internal static string PromptUpdatingTags {
            get {
                return ResourceManager.GetString("PromptUpdatingTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Authour.
        /// </summary>
        internal static string UnknownAuthor {
            get {
                return ResourceManager.GetString("UnknownAuthor", resourceCulture);
            }
        }
    }
}
