//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBookMan.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BookMan.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Fiction Book file is corrupted of badly structured..
        /// </summary>
        internal static string ErrorInvalidXml {
            get {
                return ResourceManager.GetString("ErrorInvalidXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading file or file does not exist..
        /// </summary>
        internal static string ErrorIO {
            get {
                return ResourceManager.GetString("ErrorIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string GenreAction {
            get {
                return ResourceManager.GetString("GenreAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adventure.
        /// </summary>
        internal static string GenreAdventure {
            get {
                return ResourceManager.GetString("GenreAdventure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antique.
        /// </summary>
        internal static string GenreAntique {
            get {
                return ResourceManager.GetString("GenreAntique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business.
        /// </summary>
        internal static string GenreBusiness {
            get {
                return ResourceManager.GetString("GenreBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child.
        /// </summary>
        internal static string GenreChild {
            get {
                return ResourceManager.GetString("GenreChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classic Prose.
        /// </summary>
        internal static string GenreClassic {
            get {
                return ResourceManager.GetString("GenreClassic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computers.
        /// </summary>
        internal static string GenreComp {
            get {
                return ResourceManager.GetString("GenreComp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detective.
        /// </summary>
        internal static string GenreDetective {
            get {
                return ResourceManager.GetString("GenreDetective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dramaturgy.
        /// </summary>
        internal static string GenreDramaturgy {
            get {
                return ResourceManager.GetString("GenreDramaturgy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erotica.
        /// </summary>
        internal static string GenreErotica {
            get {
                return ResourceManager.GetString("GenreErotica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fantasy.
        /// </summary>
        internal static string GenreFantasy {
            get {
                return ResourceManager.GetString("GenreFantasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string GenreHistory {
            get {
                return ResourceManager.GetString("GenreHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string GenreHome {
            get {
                return ResourceManager.GetString("GenreHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humor.
        /// </summary>
        internal static string GenreHumor {
            get {
                return ResourceManager.GetString("GenreHumor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Love Stories.
        /// </summary>
        internal static string GenreLove {
            get {
                return ResourceManager.GetString("GenreLove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modern Prose.
        /// </summary>
        internal static string GenreModern {
            get {
                return ResourceManager.GetString("GenreModern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poetry.
        /// </summary>
        internal static string GenrePoetry {
            get {
                return ResourceManager.GetString("GenrePoetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prose.
        /// </summary>
        internal static string GenreProse {
            get {
                return ResourceManager.GetString("GenreProse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to References.
        /// </summary>
        internal static string GenreRef {
            get {
                return ResourceManager.GetString("GenreRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Religion.
        /// </summary>
        internal static string GenreRel {
            get {
                return ResourceManager.GetString("GenreRel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Science.
        /// </summary>
        internal static string GenreSci {
            get {
                return ResourceManager.GetString("GenreSci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicine.
        /// </summary>
        internal static string GenreSciMedi {
            get {
                return ResourceManager.GetString("GenreSciMedi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natural Science.
        /// </summary>
        internal static string GenreSciNatural {
            get {
                return ResourceManager.GetString("GenreSciNatural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Psychology.
        /// </summary>
        internal static string GenreSciPsycho {
            get {
                return ResourceManager.GetString("GenreSciPsycho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Science.
        /// </summary>
        internal static string GenreSciSocial {
            get {
                return ResourceManager.GetString("GenreSciSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Science Fiction.
        /// </summary>
        internal static string GenreSf {
            get {
                return ResourceManager.GetString("GenreSf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thriller.
        /// </summary>
        internal static string GenreThriller {
            get {
                return ResourceManager.GetString("GenreThriller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiction Book.
        /// </summary>
        internal static string NameFb2 {
            get {
                return ResourceManager.GetString("NameFb2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local File.
        /// </summary>
        internal static string NameLocal {
            get {
                return ResourceManager.GetString("NameLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing metadata....
        /// </summary>
        internal static string PromptParsingMetadata {
            get {
                return ResourceManager.GetString("PromptParsingMetadata", resourceCulture);
            }
        }
    }
}
